<?php

$query = '';

// Show search
if (isset($_GET['q']))
{	
	$query = $_GET['q'];
}

?>

<html>
<head>
	<meta charset="utf-8">
    <script src="external/jquery.js"></script>
    
    <!-- SPARQL queries -->
    <script src="js/ala-hero.js"></script> 
    
	<!-- altmetric -->
	<!-- 
	<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script>
	-->
    
	<style>
		body {
			padding-left:40px;
			padding-right:40px;
			font-family: sans-serif;
		}
		
/* -------------------------------------------------------------------------------------*/
/* display taxa as a grid of thumbnails */
.taxa-grid {
}

.taxa-thumbnail {
	position:relative;
	float:left; 
	width:100px;
	height:100px;
	border:1px solid rgb(192,192,192);
	margin:5px;
	background-color:white;
}

.taxa-thumbnail span {
	font-size:10px;
	position:absolute;
	left:0px;
	top:0px;
	width:100%;
	background-color:rgba(0, 0, 0, 0.4);
	color:white;
	z-index:10;
}		

	</style>
</head>
<body>
	<div>
		<div style="display:block;float:left;">Hero<br /> images</div>
		<div>
			<form action="alahero.php">
				<input style="font-weight:lighter;margin-left:30px;color:rgb(56,64,71);font-size:20px;height:36px;display:block;float:left;width:400px;border:1px solid rgb(135,135,135);padding-left:4px;" id="search" placeholder="Pauropsalta herveyensis Owen & Moulds, 2016" name="q" value="<?php echo $query; ?>"/>
			</form>
			
		</div>
	</div>
	<div style="clear:both;"></div>
	
	<div>
		<p>This demo shows compares existing images for taxa in ALA with images that are  available from the <a href="https://zenodo.org/communities/biosyslit/?page=1&size=20">Biodiversity Literature Repository</a> (BLR). Images in the BLR are extracted from the recent taxonomic literature, and maybe the only source of imagery for newly described species. The demo is "live" in that all results are generated by querying <a href="https://ozymandias-demo.herokuapp.com">Ozymandias</a>.</p>
	
	</div>
		
	
	<div>
		<h1 id="header"></h1>
	</div>
	
	<div>
	
		<table width="100%">
			<tr><th width="50%">ALA (images currently in Atlas of Living Australia)</th><th>Ozymandias (images from BLR)</th></tr>
			<tr>
				<td style="border-right:1px solid rgb(192,192,192);">
					<div id="ala"></div>
				</td>

				<td>
					<div id="hero"></div>
				</td>
			</tr>
		</table>


		
	</div>
	
	<div>
		
		
		<h4>Examples</h4>
		<ul>
			<li><a href="alahero.php?q=Trigonopterus Fauvel, 1862">Trigonopterus Fauvel, 1862</a> (recently described weevil species)</li>
			<li><a href="alahero.php?q=Austrarchaea+Forster+%26+Platnick%2C+1984">Austrarchaea Forster & Platnick, 1984</a> (new spider species, multiple images per species)</li>
			
			<li><a href="alahero.php?q=Diaprograpta Simon, 1909">Diaprograpta Simon, 1909</a></li>
			
		</ul>
		
		<p>Feel free to try other examples, but remember that (for the purposes of this demo) the taxon name <strong>must be for an animal in AFD</strong>,
		and the name <strong>must be exactly</strong> as in the corresponding ALA page. This is because all the data comes from 
		<a href="https://ozymandias-demo.herokuapp.com/">Ozymandias</a> (which uses data from AFD), and 
		the demo doesn't do approximate search matching like the ALA website itself, it simply takes the taxon name as given and searches on that. 
		</p>
	
	
	</div>
	
<?php

if ($query != "")
{
?>
	<script>
	
	var name = '<?php echo $query; ?>';

	$('#ala').html('');
	$('#hero').html('');
	
	$('#header').html(name);
	
	child_taxa_images_ala(name, 'ala');
	
	child_taxa_images_blr(name, 'hero');
	
	</script>
<?php
}	
?>

	
</body>
</html>

